require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReabilitacaosController do

  # This should return the minimal set of attributes required to create a valid
  # Reabilitacao. As you add validations to Reabilitacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReabilitacaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all reabilitacaos as @reabilitacaos" do
      reabilitacao = Reabilitacao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reabilitacaos).should eq([reabilitacao])
    end
  end

  describe "GET show" do
    it "assigns the requested reabilitacao as @reabilitacao" do
      reabilitacao = Reabilitacao.create! valid_attributes
      get :show, {:id => reabilitacao.to_param}, valid_session
      assigns(:reabilitacao).should eq(reabilitacao)
    end
  end

  describe "GET new" do
    it "assigns a new reabilitacao as @reabilitacao" do
      get :new, {}, valid_session
      assigns(:reabilitacao).should be_a_new(Reabilitacao)
    end
  end

  describe "GET edit" do
    it "assigns the requested reabilitacao as @reabilitacao" do
      reabilitacao = Reabilitacao.create! valid_attributes
      get :edit, {:id => reabilitacao.to_param}, valid_session
      assigns(:reabilitacao).should eq(reabilitacao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reabilitacao" do
        expect {
          post :create, {:reabilitacao => valid_attributes}, valid_session
        }.to change(Reabilitacao, :count).by(1)
      end

      it "assigns a newly created reabilitacao as @reabilitacao" do
        post :create, {:reabilitacao => valid_attributes}, valid_session
        assigns(:reabilitacao).should be_a(Reabilitacao)
        assigns(:reabilitacao).should be_persisted
      end

      it "redirects to the created reabilitacao" do
        post :create, {:reabilitacao => valid_attributes}, valid_session
        response.should redirect_to(Reabilitacao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reabilitacao as @reabilitacao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reabilitacao.any_instance.stub(:save).and_return(false)
        post :create, {:reabilitacao => {  }}, valid_session
        assigns(:reabilitacao).should be_a_new(Reabilitacao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reabilitacao.any_instance.stub(:save).and_return(false)
        post :create, {:reabilitacao => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reabilitacao" do
        reabilitacao = Reabilitacao.create! valid_attributes
        # Assuming there are no other reabilitacaos in the database, this
        # specifies that the Reabilitacao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reabilitacao.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => reabilitacao.to_param, :reabilitacao => { "these" => "params" }}, valid_session
      end

      it "assigns the requested reabilitacao as @reabilitacao" do
        reabilitacao = Reabilitacao.create! valid_attributes
        put :update, {:id => reabilitacao.to_param, :reabilitacao => valid_attributes}, valid_session
        assigns(:reabilitacao).should eq(reabilitacao)
      end

      it "redirects to the reabilitacao" do
        reabilitacao = Reabilitacao.create! valid_attributes
        put :update, {:id => reabilitacao.to_param, :reabilitacao => valid_attributes}, valid_session
        response.should redirect_to(reabilitacao)
      end
    end

    describe "with invalid params" do
      it "assigns the reabilitacao as @reabilitacao" do
        reabilitacao = Reabilitacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reabilitacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => reabilitacao.to_param, :reabilitacao => {  }}, valid_session
        assigns(:reabilitacao).should eq(reabilitacao)
      end

      it "re-renders the 'edit' template" do
        reabilitacao = Reabilitacao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reabilitacao.any_instance.stub(:save).and_return(false)
        put :update, {:id => reabilitacao.to_param, :reabilitacao => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reabilitacao" do
      reabilitacao = Reabilitacao.create! valid_attributes
      expect {
        delete :destroy, {:id => reabilitacao.to_param}, valid_session
      }.to change(Reabilitacao, :count).by(-1)
    end

    it "redirects to the reabilitacaos list" do
      reabilitacao = Reabilitacao.create! valid_attributes
      delete :destroy, {:id => reabilitacao.to_param}, valid_session
      response.should redirect_to(reabilitacaos_url)
    end
  end

end
