# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)

Distrito.create!(:nome => "AVEIRO")
Distrito.create!(:nome => "BEJA")
Distrito.create!(:nome => "BRAGA")
Distrito.create!(:nome => "BRAGANÇA")
Distrito.create!(:nome => "CASTELO BRANCO")
Distrito.create!(:nome => "COIMBRA")
Distrito.create!(:nome => "ÉVORA")
Distrito.create!(:nome => "FARO")
Distrito.create!(:nome => "GUARDA")
Distrito.create!(:nome => "LEIRIA")
Distrito.create!(:nome => "LISBOA")
Distrito.create!(:nome => "PORTALEGRE")
Distrito.create!(:nome => "PORTO")
Distrito.create!(:nome => "SANTARÉM")
Distrito.create!(:nome => "SETÚBAL")
Distrito.create!(:nome => "VIANA DO CASTELO")
Distrito.create!(:nome => "VILA REAL")
Distrito.create!(:nome => "VISEU")
Distrito.create!(:nome => "ILHA DA MADEIRA (MADEIRA)")
Distrito.create!(:nome => "ILHA DE PORTO SANTO (MADEIRA)")
Distrito.create!(:nome => "ILHA DE SANTA MARIA (AÇORES)")
Distrito.create!(:nome => "ILHA DE SÃO MIGUEL (AÇORES)")
Distrito.create!(:nome => "ILHA TERCEIRA (AÇORES)")
Distrito.create!(:nome => "ILHA DA GRACIOSA (AÇORES)")
Distrito.create!(:nome => "ILHA DE SÃO JORGE (AÇORES)")
Distrito.create!(:nome => "ILHA DO PICO (AÇORES)")
Distrito.create!(:nome => "ILHA DO FAIAL (AÇORES)")
Distrito.create!(:nome => "ILHA DAS FLORES (AÇORES)")
Distrito.create!(:nome => "ILHA DO CORVO (AÇORES)")
Concelho.create!(:distrito_id => 1, :nome => "ÁGUEDA")
Concelho.create!(:distrito_id => 1, :nome => "ALBERGARIA-A-VELHA")
Concelho.create!(:distrito_id => 1, :nome => "ANADIA")
Concelho.create!(:distrito_id => 1, :nome => "AROUCA")
Concelho.create!(:distrito_id => 1, :nome => "AVEIRO")
Concelho.create!(:distrito_id => 1, :nome => "CASTELO DE PAIVA")
Concelho.create!(:distrito_id => 1, :nome => "ESPINHO")
Concelho.create!(:distrito_id => 1, :nome => "ESTARREJA")
Concelho.create!(:distrito_id => 1, :nome => "SANTA MARIA DA FEIRA")
Concelho.create!(:distrito_id => 1, :nome => "ÍLHAVO")
Concelho.create!(:distrito_id => 1, :nome => "MEALHADA")
Concelho.create!(:distrito_id => 1, :nome => "MURTOSA")
Concelho.create!(:distrito_id => 1, :nome => "OLIVEIRA DE AZEMÉIS")
Concelho.create!(:distrito_id => 1, :nome => "OLIVEIRA DO BAIRRO")
Concelho.create!(:distrito_id => 1, :nome => "OVAR")
Concelho.create!(:distrito_id => 1, :nome => "SÃO JOÃO DA MADEIRA")
Concelho.create!(:distrito_id => 1, :nome => "SEVER DO VOUGA")
Concelho.create!(:distrito_id => 1, :nome => "VAGOS")
Concelho.create!(:distrito_id => 1, :nome => "VALE DE CAMBRA")
Concelho.create!(:distrito_id => 2, :nome => "ALJUSTREL")
Concelho.create!(:distrito_id => 2, :nome => "ALMODÔVAR")
Concelho.create!(:distrito_id => 2, :nome => "ALVITO")
Concelho.create!(:distrito_id => 2, :nome => "BARRANCOS")
Concelho.create!(:distrito_id => 2, :nome => "BEJA")
Concelho.create!(:distrito_id => 2, :nome => "CASTRO VERDE")
Concelho.create!(:distrito_id => 2, :nome => "CUBA")
Concelho.create!(:distrito_id => 2, :nome => "FERREIRA DO ALENTEJO")
Concelho.create!(:distrito_id => 2, :nome => "MÉRTOLA")
Concelho.create!(:distrito_id => 2, :nome => "MOURA")
Concelho.create!(:distrito_id => 2, :nome => "ODEMIRA")
Concelho.create!(:distrito_id => 2, :nome => "OURIQUE")
Concelho.create!(:distrito_id => 2, :nome => "SERPA")
Concelho.create!(:distrito_id => 2, :nome => "VIDIGUEIRA")
Concelho.create!(:distrito_id => 3, :nome => "AMARES")
Concelho.create!(:distrito_id => 3, :nome => "BARCELOS")
Concelho.create!(:distrito_id => 3, :nome => "BRAGA")
Concelho.create!(:distrito_id => 3, :nome => "CABECEIRAS DE BASTO")
Concelho.create!(:distrito_id => 3, :nome => "CELORICO DE BASTO")
Concelho.create!(:distrito_id => 3, :nome => "ESPOSENDE")
Concelho.create!(:distrito_id => 3, :nome => "FAFE")
Concelho.create!(:distrito_id => 3, :nome => "GUIMARÃES")
Concelho.create!(:distrito_id => 3, :nome => "PÓVOA DE LANHOSO")
Concelho.create!(:distrito_id => 3, :nome => "TERRAS DE BOURO")
Concelho.create!(:distrito_id => 3, :nome => "VIEIRA DO MINHO")
Concelho.create!(:distrito_id => 3, :nome => "VILA NOVA DE FAMALICÃO")
Concelho.create!(:distrito_id => 3, :nome => "VILA VERDE")
Concelho.create!(:distrito_id => 3, :nome => "VIZELA")
Concelho.create!(:distrito_id => 4, :nome => "ALFÂNDEGA DA FÉ")
Concelho.create!(:distrito_id => 4, :nome => "BRAGANÇA")
Concelho.create!(:distrito_id => 4, :nome => "CARRAZEDA DE ANSIÃES")
Concelho.create!(:distrito_id => 4, :nome => "FREIXO DE ESPADA À CINTA")
Concelho.create!(:distrito_id => 4, :nome => "MACEDO DE CAVALEIROS")
Concelho.create!(:distrito_id => 4, :nome => "MIRANDA DO DOURO")
Concelho.create!(:distrito_id => 4, :nome => "MIRANDELA")
Concelho.create!(:distrito_id => 4, :nome => "MOGADOURO")
Concelho.create!(:distrito_id => 4, :nome => "TORRE DE MONCORVO")
Concelho.create!(:distrito_id => 4, :nome => "VILA FLOR")
Concelho.create!(:distrito_id => 4, :nome => "VIMIOSO")
Concelho.create!(:distrito_id => 4, :nome => "VINHAIS")
Concelho.create!(:distrito_id => 5, :nome => "BELMONTE")
Concelho.create!(:distrito_id => 5, :nome => "CASTELO BRANCO")
Concelho.create!(:distrito_id => 5, :nome => "COVILHÃ")
Concelho.create!(:distrito_id => 5, :nome => "FUNDÃO")
Concelho.create!(:distrito_id => 5, :nome => "IDANHA-A-NOVA")
Concelho.create!(:distrito_id => 5, :nome => "OLEIROS")
Concelho.create!(:distrito_id => 5, :nome => "PENAMACOR")
Concelho.create!(:distrito_id => 5, :nome => "PROENÇA-A-NOVA")
Concelho.create!(:distrito_id => 5, :nome => "SERTÃ")
Concelho.create!(:distrito_id => 5, :nome => "VILA DE REI")
Concelho.create!(:distrito_id => 5, :nome => "VILA VELHA DE RÓDÃO")
Concelho.create!(:distrito_id => 6, :nome => "ARGANIL")
Concelho.create!(:distrito_id => 6, :nome => "CANTANHEDE")
Concelho.create!(:distrito_id => 6, :nome => "COIMBRA")
Concelho.create!(:distrito_id => 6, :nome => "CONDEIXA-A-NOVA")
Concelho.create!(:distrito_id => 6, :nome => "FIGUEIRA DA FOZ")
Concelho.create!(:distrito_id => 6, :nome => "GÓIS")
Concelho.create!(:distrito_id => 6, :nome => "LOUSÃ")
Concelho.create!(:distrito_id => 6, :nome => "MIRA")
Concelho.create!(:distrito_id => 6, :nome => "MIRANDA DO CORVO")
Concelho.create!(:distrito_id => 6, :nome => "MONTEMOR-O-VELHO")
Concelho.create!(:distrito_id => 6, :nome => "OLIVEIRA DO HOSPITAL")
Concelho.create!(:distrito_id => 6, :nome => "PAMPILHOSA DA SERRA")
Concelho.create!(:distrito_id => 6, :nome => "PENACOVA")
Concelho.create!(:distrito_id => 6, :nome => "PENELA")
Concelho.create!(:distrito_id => 6, :nome => "SOURE")
Concelho.create!(:distrito_id => 6, :nome => "TÁBUA")
Concelho.create!(:distrito_id => 6, :nome => "VILA NOVA DE POIARES")
Concelho.create!(:distrito_id => 7, :nome => "ALANDROAL")
Concelho.create!(:distrito_id => 7, :nome => "ARRAIOLOS")
Concelho.create!(:distrito_id => 7, :nome => "BORBA")
Concelho.create!(:distrito_id => 7, :nome => "ESTREMOZ")
Concelho.create!(:distrito_id => 7, :nome => "ÉVORA")
Concelho.create!(:distrito_id => 7, :nome => "MONTEMOR-O-NOVO")
Concelho.create!(:distrito_id => 7, :nome => "MORA")
Concelho.create!(:distrito_id => 7, :nome => "MOURÃO")
Concelho.create!(:distrito_id => 7, :nome => "PORTEL")
Concelho.create!(:distrito_id => 7, :nome => "REDONDO")
Concelho.create!(:distrito_id => 7, :nome => "REGUENGOS DE MONSARAZ")
Concelho.create!(:distrito_id => 7, :nome => "VENDAS NOVAS")
Concelho.create!(:distrito_id => 7, :nome => "VIANA DO ALENTEJO")
Concelho.create!(:distrito_id => 7, :nome => "VILA VIÇOSA")
Concelho.create!(:distrito_id => 8, :nome => "ALBUFEIRA")
Concelho.create!(:distrito_id => 8, :nome => "ALCOUTIM")
Concelho.create!(:distrito_id => 8, :nome => "ALJEZUR")
Concelho.create!(:distrito_id => 8, :nome => "CASTRO MARIM")
Concelho.create!(:distrito_id => 8, :nome => "FARO")
Concelho.create!(:distrito_id => 8, :nome => "LAGOA")
Concelho.create!(:distrito_id => 8, :nome => "LAGOS")
Concelho.create!(:distrito_id => 8, :nome => "LOULÉ")
Concelho.create!(:distrito_id => 8, :nome => "MONCHIQUE")
Concelho.create!(:distrito_id => 8, :nome => "OLHÃO")
Concelho.create!(:distrito_id => 8, :nome => "PORTIMÃO")
Concelho.create!(:distrito_id => 8, :nome => "SÃO BRÁS DE ALPORTEL")
Concelho.create!(:distrito_id => 8, :nome => "SILVES")
Concelho.create!(:distrito_id => 8, :nome => "TAVIRA")
Concelho.create!(:distrito_id => 8, :nome => "VILA DO BISPO")
Concelho.create!(:distrito_id => 8, :nome => "VILA REAL DE SANTO ANTÓNIO")
Concelho.create!(:distrito_id => 9, :nome => "AGUIAR DA BEIRA")
Concelho.create!(:distrito_id => 9, :nome => "ALMEIDA")
Concelho.create!(:distrito_id => 9, :nome => "CELORICO DA BEIRA")
Concelho.create!(:distrito_id => 9, :nome => "FIGUEIRA DE CASTELO RODRIGO")
Concelho.create!(:distrito_id => 9, :nome => "FORNOS DE ALGODRES")
Concelho.create!(:distrito_id => 9, :nome => "GOUVEIA")
Concelho.create!(:distrito_id => 9, :nome => "GUARDA")
Concelho.create!(:distrito_id => 9, :nome => "MANTEIGAS")
Concelho.create!(:distrito_id => 9, :nome => "MÊDA")
Concelho.create!(:distrito_id => 9, :nome => "PINHEL")
Concelho.create!(:distrito_id => 9, :nome => "SABUGAL")
Concelho.create!(:distrito_id => 9, :nome => "SEIA")
Concelho.create!(:distrito_id => 9, :nome => "TRANCOSO")
Concelho.create!(:distrito_id => 9, :nome => "VILA NOVA DE FOZ CÔA")
Concelho.create!(:distrito_id => 10, :nome => "ALCOBAÇA")
Concelho.create!(:distrito_id => 10, :nome => "ALVAIÁZERE")
Concelho.create!(:distrito_id => 10, :nome => "ANSIÃO")
Concelho.create!(:distrito_id => 10, :nome => "BATALHA")
Concelho.create!(:distrito_id => 10, :nome => "BOMBARRAL")
Concelho.create!(:distrito_id => 10, :nome => "CALDAS DA RAINHA")
Concelho.create!(:distrito_id => 10, :nome => "CASTANHEIRA DE PÊRA")
Concelho.create!(:distrito_id => 10, :nome => "FIGUEIRÓ DOS VINHOS")
Concelho.create!(:distrito_id => 10, :nome => "LEIRIA")
Concelho.create!(:distrito_id => 10, :nome => "MARINHA GRANDE")
Concelho.create!(:distrito_id => 10, :nome => "NAZARÉ")
Concelho.create!(:distrito_id => 10, :nome => "ÓBIDOS")
Concelho.create!(:distrito_id => 10, :nome => "PEDRÓGÃO GRANDE")
Concelho.create!(:distrito_id => 10, :nome => "PENICHE")
Concelho.create!(:distrito_id => 10, :nome => "POMBAL")
Concelho.create!(:distrito_id => 10, :nome => "PORTO DE MÓS")
Concelho.create!(:distrito_id => 11, :nome => "ALENQUER")
Concelho.create!(:distrito_id => 11, :nome => "ARRUDA DOS VINHOS")
Concelho.create!(:distrito_id => 11, :nome => "AZAMBUJA")
Concelho.create!(:distrito_id => 11, :nome => "CADAVAL")
Concelho.create!(:distrito_id => 11, :nome => "CASCAIS")
Concelho.create!(:distrito_id => 11, :nome => "LISBOA")
Concelho.create!(:distrito_id => 11, :nome => "LOURES")
Concelho.create!(:distrito_id => 11, :nome => "LOURINHÃ")
Concelho.create!(:distrito_id => 11, :nome => "MAFRA")
Concelho.create!(:distrito_id => 11, :nome => "OEIRAS")
Concelho.create!(:distrito_id => 11, :nome => "SINTRA")
Concelho.create!(:distrito_id => 11, :nome => "SOBRAL DE MONTE AGRAÇO")
Concelho.create!(:distrito_id => 11, :nome => "TORRES VEDRAS")
Concelho.create!(:distrito_id => 11, :nome => "VILA FRANCA DE XIRA")
Concelho.create!(:distrito_id => 11, :nome => "AMADORA")
Concelho.create!(:distrito_id => 11, :nome => "ODIVELAS")
Concelho.create!(:distrito_id => 12, :nome => "ALTER DO CHÃO")
Concelho.create!(:distrito_id => 12, :nome => "ARRONCHES")
Concelho.create!(:distrito_id => 12, :nome => "AVIS")
Concelho.create!(:distrito_id => 12, :nome => "CAMPO MAIOR")
Concelho.create!(:distrito_id => 12, :nome => "CASTELO DE VIDE")
Concelho.create!(:distrito_id => 12, :nome => "CRATO")
Concelho.create!(:distrito_id => 12, :nome => "ELVAS")
Concelho.create!(:distrito_id => 12, :nome => "FRONTEIRA")
Concelho.create!(:distrito_id => 12, :nome => "GAVIÃO")
Concelho.create!(:distrito_id => 12, :nome => "MARVÃO")
Concelho.create!(:distrito_id => 12, :nome => "MONFORTE")
Concelho.create!(:distrito_id => 12, :nome => "NISA")
Concelho.create!(:distrito_id => 12, :nome => "PONTE DE SOR")
Concelho.create!(:distrito_id => 12, :nome => "PORTALEGRE")
Concelho.create!(:distrito_id => 12, :nome => "SOUSEL")
Concelho.create!(:distrito_id => 13, :nome => "AMARANTE")
Concelho.create!(:distrito_id => 13, :nome => "BAIÃO")
Concelho.create!(:distrito_id => 13, :nome => "FELGUEIRAS")
Concelho.create!(:distrito_id => 13, :nome => "GONDOMAR")
Concelho.create!(:distrito_id => 13, :nome => "LOUSADA")
Concelho.create!(:distrito_id => 13, :nome => "MAIA")
Concelho.create!(:distrito_id => 13, :nome => "MARCO DE CANAVESES")
Concelho.create!(:distrito_id => 13, :nome => "MATOSINHOS")
Concelho.create!(:distrito_id => 13, :nome => "PAÇOS DE FERREIRA")
Concelho.create!(:distrito_id => 13, :nome => "PAREDES")
Concelho.create!(:distrito_id => 13, :nome => "PENAFIEL")
Concelho.create!(:distrito_id => 13, :nome => "PORTO")
Concelho.create!(:distrito_id => 13, :nome => "PÓVOA DE VARZIM")
Concelho.create!(:distrito_id => 13, :nome => "SANTO TIRSO")
Concelho.create!(:distrito_id => 13, :nome => "VALONGO")
Concelho.create!(:distrito_id => 13, :nome => "VILA DO CONDE")
Concelho.create!(:distrito_id => 13, :nome => "VILA NOVA DE GAIA")
Concelho.create!(:distrito_id => 13, :nome => "TROFA")
Concelho.create!(:distrito_id => 14, :nome => "ABRANTES")
Concelho.create!(:distrito_id => 14, :nome => "ALCANENA")
Concelho.create!(:distrito_id => 14, :nome => "ALMEIRIM")
Concelho.create!(:distrito_id => 14, :nome => "ALPIARÇA")
Concelho.create!(:distrito_id => 14, :nome => "BENAVENTE")
Concelho.create!(:distrito_id => 14, :nome => "CARTAXO")
Concelho.create!(:distrito_id => 14, :nome => "CHAMUSCA")
Concelho.create!(:distrito_id => 14, :nome => "CONSTÂNCIA")
Concelho.create!(:distrito_id => 14, :nome => "CORUCHE")
Concelho.create!(:distrito_id => 14, :nome => "ENTRONCAMENTO")
Concelho.create!(:distrito_id => 14, :nome => "FERREIRA DO ZÊZERE")
Concelho.create!(:distrito_id => 14, :nome => "GOLEGÃ")
Concelho.create!(:distrito_id => 14, :nome => "MAÇÃO")
Concelho.create!(:distrito_id => 14, :nome => "RIO MAIOR")
Concelho.create!(:distrito_id => 14, :nome => "SALVATERRA DE MAGOS")
Concelho.create!(:distrito_id => 14, :nome => "SANTARÉM")
Concelho.create!(:distrito_id => 14, :nome => "SARDOAL")
Concelho.create!(:distrito_id => 14, :nome => "TOMAR")
Concelho.create!(:distrito_id => 14, :nome => "TORRES NOVAS")
Concelho.create!(:distrito_id => 14, :nome => "VILA NOVA DA BARQUINHA")
Concelho.create!(:distrito_id => 14, :nome => "OURÉM")
Concelho.create!(:distrito_id => 15, :nome => "ALCÁCER DO SAL")
Concelho.create!(:distrito_id => 15, :nome => "ALCOCHETE")
Concelho.create!(:distrito_id => 15, :nome => "ALMADA")
Concelho.create!(:distrito_id => 15, :nome => "BARREIRO")
Concelho.create!(:distrito_id => 15, :nome => "GRÂNDOLA")
Concelho.create!(:distrito_id => 15, :nome => "MOITA")
Concelho.create!(:distrito_id => 15, :nome => "MONTIJO")
Concelho.create!(:distrito_id => 15, :nome => "PALMELA")
Concelho.create!(:distrito_id => 15, :nome => "SANTIAGO DO CACÉM")
Concelho.create!(:distrito_id => 15, :nome => "SEIXAL")
Concelho.create!(:distrito_id => 15, :nome => "SESIMBRA")
Concelho.create!(:distrito_id => 15, :nome => "SETÚBAL")
Concelho.create!(:distrito_id => 15, :nome => "SINES")
Concelho.create!(:distrito_id => 16, :nome => "ARCOS DE VALDEVEZ")
Concelho.create!(:distrito_id => 16, :nome => "CAMINHA")
Concelho.create!(:distrito_id => 16, :nome => "MELGAÇO")
Concelho.create!(:distrito_id => 16, :nome => "MONÇÃO")
Concelho.create!(:distrito_id => 16, :nome => "PAREDES DE COURA")
Concelho.create!(:distrito_id => 16, :nome => "PONTE DA BARCA")
Concelho.create!(:distrito_id => 16, :nome => "PONTE DE LIMA")
Concelho.create!(:distrito_id => 16, :nome => "VALENÇA")
Concelho.create!(:distrito_id => 16, :nome => "VIANA DO CASTELO")
Concelho.create!(:distrito_id => 16, :nome => "VILA NOVA DE CERVEIRA")
Concelho.create!(:distrito_id => 17, :nome => "ALIJÓ")
Concelho.create!(:distrito_id => 17, :nome => "BOTICAS")
Concelho.create!(:distrito_id => 17, :nome => "CHAVES")
Concelho.create!(:distrito_id => 17, :nome => "MESÃO FRIO")
Concelho.create!(:distrito_id => 17, :nome => "MONDIM DE BASTO")
Concelho.create!(:distrito_id => 17, :nome => "MONTALEGRE")
Concelho.create!(:distrito_id => 17, :nome => "MURÇA")
Concelho.create!(:distrito_id => 17, :nome => "PESO DA RÉGUA")
Concelho.create!(:distrito_id => 17, :nome => "RIBEIRA DE PENA")
Concelho.create!(:distrito_id => 17, :nome => "SABROSA")
Concelho.create!(:distrito_id => 17, :nome => "SANTA MARTA DE PENAGUIÃO")
Concelho.create!(:distrito_id => 17, :nome => "VALPAÇOS")
Concelho.create!(:distrito_id => 17, :nome => "VILA POUCA DE AGUIAR")
Concelho.create!(:distrito_id => 17, :nome => "VILA REAL")
Concelho.create!(:distrito_id => 18, :nome => "ARMAMAR")
Concelho.create!(:distrito_id => 18, :nome => "CARREGAL DO SAL")
Concelho.create!(:distrito_id => 18, :nome => "CASTRO DAIRE")
Concelho.create!(:distrito_id => 18, :nome => "CINFÃES")
Concelho.create!(:distrito_id => 18, :nome => "LAMEGO")
Concelho.create!(:distrito_id => 18, :nome => "MANGUALDE")
Concelho.create!(:distrito_id => 18, :nome => "MOIMENTA DA BEIRA")
Concelho.create!(:distrito_id => 18, :nome => "MORTÁGUA")
Concelho.create!(:distrito_id => 18, :nome => "NELAS")
Concelho.create!(:distrito_id => 18, :nome => "OLIVEIRA DE FRADES")
Concelho.create!(:distrito_id => 18, :nome => "PENALVA DO CASTELO")
Concelho.create!(:distrito_id => 18, :nome => "PENEDONO")
Concelho.create!(:distrito_id => 18, :nome => "RESENDE")
Concelho.create!(:distrito_id => 18, :nome => "SANTA COMBA DÃO")
Concelho.create!(:distrito_id => 18, :nome => "SÃO JOÃO DA PESQUEIRA")
Concelho.create!(:distrito_id => 18, :nome => "SÃO PEDRO DO SUL")
Concelho.create!(:distrito_id => 18, :nome => "SÁTÃO")
Concelho.create!(:distrito_id => 18, :nome => "SERNANCELHE")
Concelho.create!(:distrito_id => 18, :nome => "TABUAÇO")
Concelho.create!(:distrito_id => 18, :nome => "TAROUCA")
Concelho.create!(:distrito_id => 18, :nome => "TONDELA")
Concelho.create!(:distrito_id => 18, :nome => "VILA NOVA DE PAIVA")
Concelho.create!(:distrito_id => 18, :nome => "VISEU")
Concelho.create!(:distrito_id => 18, :nome => "VOUZELA")
Concelho.create!(:distrito_id => 19, :nome => "CALHETA")
Concelho.create!(:distrito_id => 19, :nome => "CAMARA DE LOBOS")
Concelho.create!(:distrito_id => 19, :nome => "FUNCHAL")
Concelho.create!(:distrito_id => 19, :nome => "MACHICO")
Concelho.create!(:distrito_id => 19, :nome => "PONTA DO SOL")
Concelho.create!(:distrito_id => 19, :nome => "PORTO MONIZ")
Concelho.create!(:distrito_id => 19, :nome => "RIBEIRA BRAVA")
Concelho.create!(:distrito_id => 19, :nome => "SANTA CRUZ")
Concelho.create!(:distrito_id => 19, :nome => "SANTANA")
Concelho.create!(:distrito_id => 19, :nome => "SÃO VICENTE")
Concelho.create!(:distrito_id => 20, :nome => "PORTO SANTO")
Concelho.create!(:distrito_id => 21, :nome => "VILA DO PORTO")
Concelho.create!(:distrito_id => 22, :nome => "NORDESTE")
Concelho.create!(:distrito_id => 22, :nome => "PONTA DELGADA")
Concelho.create!(:distrito_id => 22, :nome => "POVOAÇÃO")
Concelho.create!(:distrito_id => 22, :nome => "RIBEIRA GRANDE")
Concelho.create!(:distrito_id => 22, :nome => "VILA FRANCA DO CAMPO")
Concelho.create!(:distrito_id => 23, :nome => "ANGRA DO HEROÍSMO")
Concelho.create!(:distrito_id => 23, :nome => "PRAIA DA VITÓRIA")
Concelho.create!(:distrito_id => 24, :nome => "SANTA CRUZ DA GRACIOSA")
Concelho.create!(:distrito_id => 25, :nome => "CALHETA DE SÃO JORGE")
Concelho.create!(:distrito_id => 25, :nome => "VELAS")
Concelho.create!(:distrito_id => 26, :nome => "LAJES DO PICO")
Concelho.create!(:distrito_id => 26, :nome => "MADALENA")
Concelho.create!(:distrito_id => 26, :nome => "SÃO ROQUE DO PICO")
Concelho.create!(:distrito_id => 27, :nome => "HORTA")
Concelho.create!(:distrito_id => 28, :nome => "LAJES DAS FLORES")
Concelho.create!(:distrito_id => 28, :nome => "SANTA CRUZ DAS FLORES")
Concelho.create!(:distrito_id => 29, :nome => "CORVO")

Limpeza.create!(:categoria_id => 1, :categoria => 'Vegetação', :opcao => 'Com ramos sobre o leito', :resposta => 'Com ramos sobre o leito resposta 1')
Limpeza.create!(:categoria_id => 1, :categoria => 'Vegetação', :opcao => 'Com ramos e arbustos no leito', :resposta => 'resposta 2')
Limpeza.create!(:categoria_id => 1, :categoria => 'Vegetação', :opcao => 'Com obstrução parcial do leito(<25%)', :resposta => 'resposta 3')
Limpeza.create!(:categoria_id => 1, :categoria => 'Vegetação', :opcao => 'Com obstrução (entre 25 e 50% do leite)', :resposta => 'resposta 4')
Limpeza.create!(:categoria_id => 1, :categoria => 'Vegetação', :opcao => 'Com obstrução do leito (> 50%)', :resposta => 'resposta 5')
Limpeza.create!(:categoria_id => 2, :categoria => 'Árvores caídas no leito do rio', :opcao => '1 tronco', :resposta => 'resposta 6')
Limpeza.create!(:categoria_id => 2, :categoria => 'Árvores caídas no leito do rio', :opcao => 'Mais de 2 troncos', :resposta => 'reposta 7')
Limpeza.create!(:categoria_id => 2, :categoria => 'Árvores caídas no leito do rio', :opcao => 'formação de barreira (< 50%)', :resposta => 'resposta 8')
Limpeza.create!(:categoria_id => 2, :categoria => 'Árvores caídas no leito do rio', :opcao => 'formação de barreira (> 50%)', :resposta => 'resposta 9')
Limpeza.create!(:categoria_id => 3,:categoria => 'Silvados', :opcao => '1 metro', :resposta => 'resposta 10')
Limpeza.create!(:categoria_id => 3,:categoria => 'Silvados', :opcao => '2 metros ', :resposta => 'resposta 11')
Limpeza.create!(:categoria_id => 3,:categoria => 'Silvados', :opcao => 'Mais de 3 metros', :resposta => 'resposta 12')
Limpeza.create!(:categoria_id => 4,:categoria => 'Invasoras exóticas', :opcao => 'Canas', :resposta => 'resposta 13')
Limpeza.create!(:categoria_id => 4,:categoria => 'Invasoras exóticas', :opcao => 'Acácias', :resposta => 'resposta 14')
Limpeza.create!(:categoria_id => 4,:categoria => 'Invasoras exóticas', :opcao => 'Penachos', :resposta => 'resposta 15')
Limpeza.create!(:categoria_id => 5,:categoria => 'Espécies aquáticas autoctones', :opcao => 'Tabúal', :resposta => 'resposta 16')
Limpeza.create!(:categoria_id => 5,:categoria => 'Espécies aquáticas autoctones', :opcao => 'Lírios Amarelos', :resposta => 'resposta 17')
Limpeza.create!(:categoria_id => 6,:categoria => 'Espécies aquáticas exóticas', :opcao => 'Jacinto', :resposta => 'resposta 18')
Limpeza.create!(:categoria_id => 6,:categoria => 'Espécies aquáticas exóticas', :opcao => 'Azola', :resposta => 'resposta 19')
Limpeza.create!(:categoria_id => 6,:categoria => 'Espécies aquáticas exóticas', :opcao => 'Pinheirinha', :resposta => 'resposta 20')
Limpeza.create!(:categoria_id => 7,:categoria => 'Lixo doméstico', :opcao => 'Lixo (resíduos domésticos)', :resposta => 'resposta 21')
Limpeza.create!(:categoria_id => 8,:categoria => 'Lixo industrial', :opcao => 'Algumas sobras de Produção industrial', :resposta => 'resposta 22')
Limpeza.create!(:categoria_id => 8,:categoria => 'Lixo industrial', :opcao => 'Libertação de Quimicos e residuos não tratados', :resposta => 'resposta 23')
Limpeza.create!(:categoria_id => 8,:categoria => 'Lixo industrial', :opcao => 'Descargas ou acidentes de quimicos perigosos ', :resposta => 'resposta 24')
Limpeza.create!(:categoria_id => 8,:categoria => 'Lixo industrial', :opcao => 'Residuos Hospitalares e quimicos perigosos', :resposta => 'resposta 25')
Limpeza.create!(:categoria_id => 9,:categoria => 'Entulhos e restos de obras', :opcao => 'Barros e cerámicas', :resposta => 'resposta 26')
Limpeza.create!(:categoria_id => 9,:categoria => 'Entulhos e restos de obras', :opcao => 'Metais e vidros', :resposta => 'resposta 27')
Limpeza.create!(:categoria_id => 9,:categoria => 'Entulhos e restos de obras', :opcao => 'Plásticos', :resposta => 'resposta 28')
Limpeza.create!(:categoria_id => 9,:categoria => 'Entulhos e restos de obras', :opcao => 'Químicos', :resposta => 'resposta 29')
Limpeza.create!(:categoria_id => 10,:categoria => 'Sedimentação', :opcao => 'Muita', :resposta => 'resposta 30')
Limpeza.create!(:categoria_id => 10,:categoria => 'Sedimentação', :opcao => 'Normal', :resposta => 'resposta 31')
Limpeza.create!(:categoria_id => 10,:categoria => 'Sedimentação', :opcao => 'Pouca', :resposta => 'resposta 32')
Limpeza.create!(:categoria_id => 11,:categoria => 'Erosão', :opcao => 'Erosão', :resposta => 'resposta 33')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Domésticas excepcional', :resposta => 'resposta 34')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Doméstica Pontual', :resposta => 'resposta 35')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Doméstica Continua', :resposta => 'resposta 36')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Industrial excepcional', :resposta => 'resposta 37')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Industrial Pontual', :resposta => 'resposta 38')
Limpeza.create!(:categoria_id => 12,:categoria => 'Descargas de poluição', :opcao => 'Industrial Continua', :resposta => 'resposta 39')
Limpeza.create!(:categoria_id => 13,:categoria => 'Falta de água', :opcao => 'Natural', :resposta => 'resposta 40')
Limpeza.create!(:categoria_id => 13,:categoria => 'Falta de água', :opcao => 'Antrópica', :resposta => 'resposta 41')





















